### ISSUE TITLE
Create a Responsive Mental Health Webpage with Organised Content

### ISSUE THREAD

**Issue by lindanwajei2205** [lindanwajei2205/mental-health-awareness#1]
### **User Story** 
As a site user, I want to access beginner-friendly mental health information, so as to easily learn how to recognise common mental health issues and manage stress in a supportive, organised, and visually appealing layout.

**Acceptance Criteria**

- [x] The website must be fully responsive, adapting to different screen sizes
- [x] The site colour contrast, typography and alt text for non-text element must adhere to accessible guidelines
- [x] The webpage navigation menu, and contents must be well structured and adhere to standard user experience. 

**Task**

- [x] Apply responsive design techniques to the website with bootstrap ensuring the website seamlessly adapts to various screen sizes (i.e desktop, tablet, and mobile) for good user experience.
- [x] Ensure clean design with well structured content, use of colour, typography and imagery to enhance positive and calming user experience.
